#! /bin/bash

bspc config border_width	2
bspc config window_gap		0

bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_by_distance	true
bspc config history_aware_focus	true

bspc monitor -d unu di tri kvar kvin ses sep ok naŭ dek

bspc config focused_border_color	"#EDE0CE"
bspc config normal_border_color		"#2B2A27"

